sessions:
  remember: 1
name:
  length: 50
email:
  length: 255
pass:
  min_length: 6
  max_length: 50
gravatar:
  size: 50
category:
  name_length: 50
product:
  name_length: 255
quantity:
  default: 1
image:
  size: "50x50"
per_page: 9
mailer:
  host: "localhost:3000"
statuses:
  cancelled: "cancelled"
  in_progress: "in_progress"
  rejected: "rejected"
  approved: "approved"
danger: "btn-danger"
light: "btn-primary"
warning: "btn-warning"
success: "btn-success"
